---
- name: Docker 및 Docker Compose 설치 (예시)
  package:
    name:
      - docker
      - docker-compose
    state: present

- name: Docker 그룹에 사용자 추가
  user:
    name: "{{ ansible_user | default('root') }}"
    groups: docker
    append: yes

- name: Chartmuseum 디렉토리 생성
  file:
    path: "{{ chartmuseum.data_dir }}"
    state: directory

- name: Chartmuseum 컨테이너 실행 스크립트 실행 (예시)
  shell: "{{ chartmuseum.install_script }}"
  args:
    chdir: "{{ chartmuseum.data_dir }}"
