---
- name: Install httpd
  yum:
    name: httpd
    state: present

- name: Start httpd service
  service:
    name: httpd
    state: started

- name: Allow HTTP through firewall
  firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded