---
- name: Run shell script
  hosts: all
  
  tasks:
  - name: copy script
    copy:
      src: /home/ec2-user/ansible/ch4/shell-scripts/run.sh
      dest: /home/ec2-user/run.sh
      mode: '0755'
 
  - name: Run shell script
    shell: /home/ec2-user/run.sh
    # args:
    #   executable: /bin/bash
    # register: script_result
    # changed_when: script_result.rc == 0
    # failed_when: script_result.rc != 0
    # retries: 3
    # delay: 10
    # when: ansible_check_mode is not defined or not ansible_check_mode