---
- name: Installing packages   
  hosts: targets             # localhost 대신 inventory의 targets 그룹 사용
  become: yes               # root 권한 사용
  
  tasks:                      
  - name: Install apache     # Apache 웹 서버 설치
    dnf: 
      name: httpd
      state: present

  - name: Start apache      # Apache 서비스 시작 및 자동 시작 설정
    service:
      name: httpd
      state: started
      enabled: yes
