---
- name: Add or update user password
  hosts: all

  tasks:
  - name: change password
    become: true
    user: 
      name: "{{ item }}"
      update_password: always
      password: "{{ newpassword|password_hash('sha512') }}"
    with_items:
      - user1
      - user2
      - user3

# 패스워드 변경 후 확인 명령 : ssh -i ~/.ssh/id_rsa ec2-user@54.180.109.214 passwd -S <user>