---
- name: Docker 및 Docker Compose 설치 (예시)
  package:
    name:
      - docker
      - docker-compose
    state: present

- name: Docker 그룹에 사용자 추가
  user:
    name: "{{ ansible_user | default('root') }}"
    groups: docker
    append: yes

- name: CoreDNS 디렉토리 생성
  file:
    path: "{{ coredns.config_dir }}"
    state: directory

- name: Corefile 템플릿 배포 (예시)
  template:
    src: Corefile.j2
    dest: "{{ coredns.corefile_path }}"

- name: hosts 파일 배포 (예시)
  copy:
    src: hosts.txt
    dest: "{{ coredns.hosts_file }}"

- name: CoreDNS 컨테이너 실행 스크립트 실행 (예시)
  shell: "{{ coredns.install_script_path }}"
  args:
    chdir: "{{ coredns.config_dir }}"
