---
- name: Playbook for creating user
  hosts: all

  tasks:
  - name: create users
    become: true 
    user:
      name: "{{ item }}"
      home: /home/{{ item }}
      shell: /bin/bash
    with_items:
      - user1
      - user2
      - user3

# 생성 후 확인 명령 : id <user>

